### ISSUE TITLE
Vive Lighthouse (SteamVR v1) Support

### ISSUE THREAD

**Issue by ShayBox** [ShayBox/Lighthouse#1]
If there's anyone that has Vive lighthouses that can help test please comment, I would like to add support but I can't test.

If you know how to add the support yourself I welcome a pull request as well. 

The current code does not have support for it.

**Comment by tsjost** [comment]
The Vive base stations' names are "HTC BS <6 hex chars>" so doing `.any(|name| name.contains("LHB-") || name.contains("HTC BS"))` will filter them, but when running it just panics (somewhere in `discover_characteristics()` it seems):
```
$ RUST_BACKTRACE=full target/x86_64-unknown-linux-gnu/release/lighthouse on
thread '<unnamed>' panicked at 'byte index 4 is out of bounds of `00`',
    ~/.cargo/registry/src/github.com-1ecc6299db9ec823/btleplug-0.7.1/src/bluez/mod.rs:69:34
stack backtrace:
...stuff...
  13:     0x55dcd75ab6ed - rust_begin_unwind
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/panicking.rs:493:5
  14:     0x55dcd75461b0 - core::panicking::panic_fmt::hb1f208d1d41afb98
                               at /build/rust/src/rustc-1.50.0-src/library/core/src/panicking.rs:92:14
  15:     0x55dcd7546ff6 - core::str::slice_error_fail::h86df84d5aa212376
  16:     0x55dcd753ff97 - <btleplug::bluez::Handle as core::str::traits::FromStr>::from_str::{{closure}}::h110924aab90d7fd9
  17:     0x55dcd753f73a - <btleplug::bluez::Handle as core::str::traits::FromStr>::from_str::ha119d8f14d63c1b6
  18:     0x55dcd754219d - btleplug::bluez::adapter::Adapter::add_attribute::haf859addd75a9512
  19:     0x55dcd7544500 - <F as dbus::blocking::MakeSignal<alloc::boxed::Box<dyn core::ops::function::FnMut<(dbus::message::Message,&dbus::blocking::SyncConnection)>+Output = bool+core::marker::Sync+core::marker::Send>,S,dbus::blocking::SyncConnection>>::make::{{closure}}::h44aa8441536ca9b3
  20:     0x55dcd7530aba - std::sys_common::backtrace::__rust_begin_short_backtrace::he6cb7688f5955b92
  21:     0x55dcd753a4eb - core::ops::function::FnOnce::call_once{{vtable.shim}}::h975fc250a23ef1fc
  22:     0x55dcd75b0baa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hca777c65d7abd3ae
                               at /build/rust/src/rustc-1.50.0-src/library/alloc/src/boxed.rs:1328:9
  23:     0x55dcd75b0baa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf1012d740d1ceae6
                               at /build/rust/src/rustc-1.50.0-src/library/alloc/src/boxed.rs:1328:9
  24:     0x55dcd75b0baa - std::sys::unix::thread::Thread::new::thread_start::h03461db65b5c7c7c
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/sys/unix/thread.rs:71:17
  25:     0x7f2873ade299 - start_thread
  26:     0x7f28738bb053 - clone
  27:                0x0 - <unknown>
```

I'm not familiar with Rust so I have no idea what this means :) but I need to `systemctl restart bluetooth` after this or the program will panic _immediately_ on startup.

**Comment by ShayBox** [comment]
Interesting I never had to restart bluetooth, possibly because of an older bluez version, try this binary https://file.io/kL9jneBZOBQF

**Comment by tsjost** [comment]
I've debugged and fixed a bug in the btleplug library; `from_str` is called with `/org/bluez/hci0/dev_AC_37_43_BE_E7_0D/serviceff00`, and it's trying to extract "ff00" at the end with `trim_start_matches(char::is_alphabetic)` which is obviously not gonna work as hexchars can be alphabetic and returns just "00", and then tries to go out of bounds with [..4], hence it crashes.

With this fixed, your code is unfortunately still not working. I think the Vive protocol is a bit more involved than just connecting and sending a few bytes? The commands need the base station's ID encoded in them, which is found printed on the back of the device (or in some OpenVR database according to https://github.com/risa2000/lhctrl).

I've played around with sending different data to the base station according to the protocol documentation (https://github.com/risa2000/lhctrl/blob/master/PROTOCOL.md), and it seems the base station ID is only needed when putting it to sleep; using all 0xff with the 0x1202 command will only work when the lighthouse is already sleeping, so the ID is required to set the timeout value while it's powered on.

So for powering on the lighthouse, this works (and only doing lighthouse.write() once):
```rust
cmd = vec![0x12, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00];
```

For powering off:
```rust
cmd = vec![0x12, 0x02, 0x00, 0x01, 0xDD, 0xCC, 0xBB, 0xAA, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00];
```
Where 0xDD and 0xCC are the last 4 chars of the bluetooth name in opposite order ("HTC BS \<last byte of MAC address><0xCC><0xDD>"), and 0xAA & 0xBB can be found on the back of the lighthouse.
For example the back of the lighthouse says: `ID: 12345678`, the bluetooth name will be "HTC BS xx5678", AA is 12, BB is 34, and the command must contain `0x78, 0x56, 0x34, 0x12`. So you need to ask the user what those two hidden bytes are if they want to be able to use the sleep feature, unless there's indeed a database somewhere.

(It takes about 20 seconds from program startup until the device receives the command for some reason)
(Also only the B/primary lighthouse needs to be commanded, as the C/secondary lighthouse automagically mirrors the state of B)

**Comment by ShayBox** [comment]
I don't believe Lighthouse PM (Android app) uses that requires user input any values
<https://github.com/jeroen1602/lighthouse_pm/blob/a749d13e0f12b9a5139a3e9e5a8ed92d877a5b45/lib/lighthouseProvider/devices/ViveBaseStationDevice.dart#L24>

**Comment by tsjost** [comment]
It does ![](https://i.imgur.com/UxDZSA1.jpg)

Storage permission is only needed for shared storage, not storage internal to the app itself.

**Comment by ShayBox** [comment]
Oh interesting, does steam also ask for this? I guess then it can't be avoided, I guess a third arg to provide this that can be detected and switch into v1 code

**Comment by tsjost** [comment]
Steam doesn't, I assume they have a way to look up or calculate the IDs or something.

**Comment by ShayBox** [comment]
I created a pull request to add v1 support, moving discussion to #2
