### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by frostworx** [ShayBox/Lighthouse#3]
Not an issue, just wanted to thank you! It builds and works very fine!
Removing my tasmota wall sockets from the lighthouses now :)

**Comment by ShayBox** [comment]
I use tasmota and homeassistant to control the hmd socket power

**Comment by frostworx** [comment]
Me too :)

**Comment by frostworx** [comment]
whoops, didn't mean to leave this open for so long - sry...
